# Generated by Django 4.1.2 on 2022-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.IntegerField(),
        ),
    ]
