# Generated by Django 4.1 on 2022-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_ticketc_total_remove_ticketm_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='concert',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='concertName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='seatType',
            field=models.CharField(choices=[('V', 'VIP'), ('R', 'Regular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=50),
        ),
    ]
