# Generated by Django 4.1 on 2022-10-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_concert_artist_alter_concert_capacity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='concert',
            unique_together={('concertName', 'artist', 'venue', 'concertDate', 'timeStart', 'seatType', 'price', 'capacity')},
        ),
    ]
