# Generated by Django 4.1 on 2022-10-16 13:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_concert_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concertDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
